-- DROP TABLE Ratings;
-- DROP TABLE OfferHolders;
-- DROP TABLE Offers;
-- DROP TABLE Prices;
-- DROP TABLE ProductLinks;
-- DROP TABLE Labels;
-- ALTER TABLE Products DROP FOREIGN KEY Products_ibfk_1;
-- DROP TABLE Brands;
-- ALTER TABLE Products DROP FOREIGN KEY Products_ibfk_2;
-- DROP TABLE Images;
-- DROP TABLE Products;

DELETE FROM Ratings; DELETE FROM OfferHolders; DELETE FROM Offers; DELETE FROM Prices; DELETE FROM ProductLinks; DELETE FROM Labels; DELETE FROM Images; DELETE FROM Products; DELETE FROM Brands;

CREATE TABLE Stores (
	ID TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
	SName TINYTEXT NOT NULL,
	
	PRIMARY KEY (ID),
	UNIQUE (SName)
);


CREATE TABLE Brands (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	BName TINYTEXT NOT NULL,
	StoreID TINYINT UNSIGNED, -- TODO another admin task, dedupe these. use to differentiate own brand eg "essentials"
	ParentID INT UNSIGNED,

	PRIMARY KEY (ID),
	FOREIGN KEY (ParentID) REFERENCES Brands(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (BName)
);


CREATE TABLE Images (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	SourceURL TEXT NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (SourceURL) -- TODO admin task, when selecting PreferredThumb delete others (at least duplicate PID StoreID), might exist due to scaling
);


CREATE TABLE Products (
	PID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PName TINYTEXT NOT NULL,
	BrandID INT UNSIGNED NOT NULL,
	PreferredThumbID INT UNSIGNED,
	PS_Count SMALLINT UNSIGNED,
	PS_SizeEach FLOAT UNSIGNED,
	PS_Unit VARCHAR(2),
	
	EntryCreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DetailsVerified BOOL DEFAULT False,
	
	PRIMARY KEY (PID),
	FOREIGN KEY (BrandID) REFERENCES Brands(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (PreferredThumbID) REFERENCES Images(ID) ON DELETE SET NULL ON UPDATE CASCADE
);


ALTER TABLE Images
ADD FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE;


CREATE TABLE ProductLinks (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PID INT UNSIGNED NOT NULL,
	UPC BIGINT UNSIGNED,
	CIN BIGINT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (UPC), -- DUPLICATE "NULL" ALLOWED.
	UNIQUE (CIN, StoreID)
);


CREATE TABLE Prices (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,

	FetchedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- for data
	FetchedDate DATE GENERATED ALWAYS AS (DATE(FetchedAt)) STORED, -- for UNIQUE constraint

	PricePence SMALLINT UNSIGNED NOT NULL,
	-- UnitPricePence SMALLINT UNSIGNED NOT NULL,
	Available BOOL DEFAULT True,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (PID, StoreID, PricePence, FetchedDate)
);


CREATE TABLE Offers (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	StoreGivenID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	OfferType TINYINT UNSIGNED NOT NULL DEFAULT 0,
	StartDate DATETIME,
	EndDate DATETIME,

	RequiresMembership BOOL,
	OnlineExclusive BOOL,

	-- AF_AnyCount TINYINT UNSIGNED,
	-- AF_ForPrice SMALLINT UNSIGNED,
	-- AF_ForCount TINYINT UNSIGNED,

	-- RR_NewPrice SMALLINT UNSIGNED,

	-- SavePerc TINYINT UNSIGNED,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (StoreGivenID, StoreID)
);


CREATE TABLE OfferHolders (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	OfferID INT UNSIGNED NOT NULL,
	PID INT UNSIGNED NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (OfferID) REFERENCES Offers(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (OfferID, PID)
);


CREATE TABLE Labels (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	VerifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	LabelType TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Param1 TEXT NOT NULL,

	PRIMARY KEY (ID),
    FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (PID, StoreID, LabelType, Param1)
);


CREATE TABLE Ratings (
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	Average FLOAT UNSIGNED NOT NULL,
	NVotes SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (StoreID) REFERENCES Stores(ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (PID, StoreID)
);