CREATE TABLE Products (
	PID INT UNSIGNED AUTO_INCREMENT,
	PName TINYTEXT NOT NULL,
	BrandID INT UNSIGNED NOT NULL,
	PreferredThumbID INT UNSIGNED,
	PS_Count SMALLINT UNSIGNED,
	PS_SizeEach FLOAT UNSIGNED,
	PS_Unit VARCHAR(2),
	
	EntryCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	EntryUpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	DetailsVerified BOOL DEFAULT False,
	
	PRIMARY KEY (PID),
	FOREIGN KEY (BrandID) REFERENCES Brands(ID),
	FOREIGN KEY (PreferredThumbID) REFERENCES Images(ID)
);

CREATE TABLE Brands (
	ID INT UNSIGNED AUTO_INCREMENT,
	BName TINYTEXT,
	ParentID INT UNSIGNED,
	-- StoreCameFrom to document own brand? TODO future.
	PRIMARY KEY (ID),
	FOREIGN KEY (ParentID) REFERENCES Brands(ID),
	UNIQUE (BName)
);

CREATE TABLE Stores (
	ID TINYINT UNSIGNED AUTO_INCREMENT,
	SName TINYTEXT,
	
	PRIMARY KEY (ID),
	UNIQUE (SName)
);

CREATE TABLE Images (
	ID INT UNSIGNED AUTO_INCREMENT,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	SourceURL TEXT NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID),
	UNIQUE (SourceURL)
);

CREATE TABLE ProductLinks (
	ID INT UNSIGNED AUTO_INCREMENT,
	PID INT UNSIGNED NOT NULL,
	UPC BIGINT UNSIGNED,
	CIN BIGINT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID),
	UNIQUE (UPC), -- DUPLICATE "NULL" ALLOWED.
	UNIQUE (CIN, StoreID)
);

CREATE TABLE Prices (
	ID INT UNSIGNED AUTO_INCREMENT,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	FetchedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PricePence SMALLINT UNSIGNED NOT NULL,
	Available BOOL DEFAULT True,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID)
);

CREATE TABLE Offers (
	ID INT UNSIGNED AUTO_INCREMENT,
	StoreGivenID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	OfferType TINYINT UNSIGNED NOT NULL DEFAULT 0,
	StartDate DATETIME,
	EndDate DATETIME,

	AF_AnyCount TINYINT UNSIGNED,
	AF_ForPrice SMALLINT UNSIGNED,
	AF_ForCount TINYINT UNSIGNED,

	RR_NewPrice SMALLINT UNSIGNED,
	SavePerc TINYINT UNSIGNED,
	
	RequiresMembership BOOL,
	OnlineExclusive BOOL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID),
	UNIQUE (StoreGivenID, StoreID)
);

CREATE TABLE OfferHolders (
	ID INT UNSIGNED AUTO_INCREMENT,
	OfferID INT UNSIGNED,
	PID INT UNSIGNED,

	PRIMARY KEY (ID),
	FOREIGN KEY (PID) REFERENCES Products(PID),
	FOREIGN KEY (OfferID) REFERENCES Offers(ID),
	UNIQUE (OfferID, PID)
);

/*CREATE TABLE Labels (
--	
--);*/

CREATE TABLE Ratings (
	ID INT UNSIGNED AUTO_INCREMENT,
	PID INT UNSIGNED NOT NULL,
	StoreID TINYINT UNSIGNED NOT NULL,
	Average FLOAT UNSIGNED NOT NULL,
	NVotes SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (StoreID) REFERENCES Stores(ID),
	UNIQUE (PID, StoreID)
);